# Generated by Django 4.2.30 on 2026-06-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_food_type'),
        ('ordermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(null=True)),
                ('quantity', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('gst_amount', models.FloatField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('customer_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordermanagement.customer')),
                ('product_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
        ),
    ]
