# Generated by Django 4.2.30 on 2026-06-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=1000, null=True)),
                ('price', models.FloatField(default=0)),
                ('tax', models.IntegerField(default=0)),
            ],
        ),
    ]
