# Generated by Django 4.2.30 on 2026-06-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='food_type',
            field=models.BooleanField(default=False),
        ),
    ]
